"use client"

import { Metadata } from 'next';
import { Inter } from 'next/font/google'
import { ChakraProvider } from '@chakra-ui/react'
import NavBar from '@/components/Navbar'
import Footer from '@/components/Footer'
import Hero from '@/components/Hero'
import Head from "next/head"



const inter = Inter({ subsets: ['latin'] })

const metadata:Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="apple-touch-icon" href="public/stock.png"/>
        <link rel="icon" type="image/x-icon" href="public/stock.png"/>
        <title>Stockify</title>
      </head>
      <body className={inter.className}>
        <ChakraProvider>
          <NavBar/>
          {children}
          <Hero/>
          {/* <Footer/> */}
        </ChakraProvider>
      </body>
    </html>
  )
}
